
@startuml
!define RECTANGLE class
skinparam linetype ortho

skinparam class {
    BackgroundColor<<source>> LightBlue
    BackgroundColor<<target>> LightGreen
}
RECTANGLE ProcedureotherTreatmenteui4rc as "Procedure-otherTreatment-eu-i4rc" <<source>> [[StructureDefinition-Procedure-otherTreatment-eu-i4rc.html]]
RECTANGLE ConditionprimaryCancereui4rc as "Condition-primaryCancer-eu-i4rc" <<source>> [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
RECTANGLE mcodetnmprimarytumorcategory as "mcode-tnm-primary-tumor-category" <<source>> [[StructureDefinition-mcode-tnm-primary-tumor-category.html]]
RECTANGLE MedicationAdministrationeui4rc as "MedicationAdministration-eu-i4rc" <<source>> [[StructureDefinition-MedicationAdministration-eu-i4rc.html]]
RECTANGLE sarcomaextentcategory as "sarcoma-extent-category" <<source>> [[StructureDefinition-sarcoma-extent-category.html]]
RECTANGLE sarcomacancerstagegroup as "sarcoma-cancer-stage-group" <<source>> [[StructureDefinition-sarcoma-cancer-stage-group.html]]
RECTANGLE sarcomalocoRegionalcategory as "sarcoma-locoRegional-category" <<source>> [[StructureDefinition-sarcoma-locoRegional-category.html]]
RECTANGLE mcodetnmregionalnodescategory as "mcode-tnm-regional-nodes-category" <<source>> [[StructureDefinition-mcode-tnm-regional-nodes-category.html]]
RECTANGLE hncancerstagegroup as "hn-cancer-stage-group" <<source>> [[StructureDefinition-hn-cancer-stage-group.html]]
RECTANGLE Encountereui4rc as "Encounter-eu-i4rc" <<source>> [[StructureDefinition-Encounter-eu-i4rc.html]]
RECTANGLE Procedureradiotheraphyeui4rc as "Procedure-radiotheraphy-eu-i4rc" <<source>> [[StructureDefinition-Procedure-radiotheraphy-eu-i4rc.html]]
RECTANGLE mcodetnmdistantmetastasescategory as "mcode-tnm-distant-metastases-category" <<source>> [[StructureDefinition-mcode-tnm-distant-metastases-category.html]]
RECTANGLE ConditionsecondaryCancereui4rc as "Condition-secondaryCancer-eu-i4rc" <<source>> [[StructureDefinition-Condition-secondaryCancer-eu-i4rc.html]]
RECTANGLE Proceduresurgeryeui4rc as "Procedure-surgery-eu-i4rc" <<source>> [[StructureDefinition-Procedure-surgery-eu-i4rc.html]]
RECTANGLE episodeOfCareeui4rc as "episodeOfCare-eu-i4rc" <<source>> [[StructureDefinition-episodeOfCare-eu-i4rc.html]]
ConditionprimaryCancereui4rc --> ConditionprimaryCancereui4rc : "value[x]"
ConditionsecondaryCancereui4rc --> ConditionprimaryCancereui4rc : "value[x]"
Encountereui4rc --> ConditionprimaryCancereui4rc : "reasonReference"
Encountereui4rc --> ConditionprimaryCancereui4rc : "condition"
episodeOfCareeui4rc --> ConditionprimaryCancereui4rc : "condition"
hncancerstagegroup --> ConditionprimaryCancereui4rc : "focus"
mcodetnmdistantmetastasescategory --> ConditionprimaryCancereui4rc : "focus"
mcodetnmprimarytumorcategory --> ConditionprimaryCancereui4rc : "focus"
mcodetnmregionalnodescategory --> ConditionprimaryCancereui4rc : "focus"
MedicationAdministrationeui4rc --> ConditionprimaryCancereui4rc : "reasonReference"
ProcedureotherTreatmenteui4rc --> ConditionprimaryCancereui4rc : "reasonReference"
Procedureradiotheraphyeui4rc --> ConditionprimaryCancereui4rc : "reasonReference"
Proceduresurgeryeui4rc --> ConditionprimaryCancereui4rc : "reasonReference"
sarcomacancerstagegroup --> ConditionprimaryCancereui4rc : "focus"
sarcomaextentcategory --> ConditionprimaryCancereui4rc : "focus"
sarcomalocoRegionalcategory --> ConditionprimaryCancereui4rc : "focus"
ProcedureotherTreatmenteui4rc -[hidden]-> ConditionprimaryCancereui4rc
ConditionprimaryCancereui4rc -[hidden]-> mcodetnmprimarytumorcategory
mcodetnmprimarytumorcategory -[hidden]-> MedicationAdministrationeui4rc
MedicationAdministrationeui4rc -[hidden]-> sarcomaextentcategory
sarcomaextentcategory -[hidden]-> sarcomacancerstagegroup
sarcomacancerstagegroup -[hidden]-> sarcomalocoRegionalcategory
sarcomalocoRegionalcategory -[hidden]-> mcodetnmregionalnodescategory
mcodetnmregionalnodescategory -[hidden]-> hncancerstagegroup
hncancerstagegroup -[hidden]-> Encountereui4rc
Encountereui4rc -[hidden]-> Procedureradiotheraphyeui4rc
Procedureradiotheraphyeui4rc -[hidden]-> mcodetnmdistantmetastasescategory
mcodetnmdistantmetastasescategory -[hidden]-> ConditionsecondaryCancereui4rc
ConditionsecondaryCancereui4rc -[hidden]-> Proceduresurgeryeui4rc
Proceduresurgeryeui4rc -[hidden]-> episodeOfCareeui4rc

legend
  | <back:LightBlue> | Source Profile |
  | <back:LightGreen> | Target Profile |
endlegend

@enduml
