
@startuml
!define RECTANGLE class
skinparam linetype ortho

skinparam class {
    BackgroundColor<<source>> LightBlue
    BackgroundColor<<target>> LightGreen
}
RECTANGLE ConditionsecondaryCancereui4rc as "Condition-secondaryCancer-eu-i4rc" <<source>> [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
RECTANGLE ConditionprimaryCancereui4rc as "Condition-primaryCancer-eu-i4rc" <<target>> [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
RECTANGLE patienteui4rc as "patient-eu-i4rc" <<target>> [[StructureDefinition-patient-eu-i4rc.html]]
ConditionsecondaryCancereui4rc --> ConditionprimaryCancereui4rc : "value[x]"
ConditionsecondaryCancereui4rc --> patienteui4rc : "subject"

legend
  | <back:LightBlue> | Source Profile |
  | <back:LightGreen> | Target Profile |
endlegend

@enduml
