
@startuml
!define RECTANGLE class
skinparam linetype ortho

skinparam class {
    BackgroundColor<<source>> LightBlue
    BackgroundColor<<target>> LightGreen
}
RECTANGLE ConditionprimaryCancereui4rc as "Condition-primaryCancer-eu-i4rc" <<source>> [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
RECTANGLE Observationdiagnosiseui4rc as "Observation-diagnosis-eu-i4rc" <<target>> [[StructureDefinition-Observation-diagnosis-eu-i4rc.html]]
RECTANGLE observationtestResulteui4rc as "observation-testResult-eu-i4rc" <<target>> [[StructureDefinition-observation-testResult-eu-i4rc.html]]
RECTANGLE patienteui4rc as "patient-eu-i4rc" <<target>> [[StructureDefinition-patient-eu-i4rc.html]]
RECTANGLE sarcomacancerstagegroup as "sarcoma-cancer-stage-group" <<target>> [[StructureDefinition-sarcoma-cancer-stage-group.html]]
RECTANGLE hncancerstagegroup as "hn-cancer-stage-group" <<target>> [[StructureDefinition-hn-cancer-stage-group.html]]
RECTANGLE Encountereui4rc as "Encounter-eu-i4rc" <<target>> [[StructureDefinition-Encounter-eu-i4rc.html]]
RECTANGLE observationyesNoeui4rc as "observation-yesNo-eu-i4rc" <<target>> [[StructureDefinition-observation-yesNo-eu-i4rc.html]]
ConditionprimaryCancereui4rc --> ConditionprimaryCancereui4rc : "value[x]"
ConditionprimaryCancereui4rc --> patienteui4rc : "subject"
ConditionprimaryCancereui4rc --> Encountereui4rc : "encounter"
ConditionprimaryCancereui4rc --> hncancerstagegroup : "assessment"
ConditionprimaryCancereui4rc --> sarcomacancerstagegroup : "assessment"
ConditionprimaryCancereui4rc --> Observationdiagnosiseui4rc : "detail"
ConditionprimaryCancereui4rc --> observationtestResulteui4rc : "detail"
ConditionprimaryCancereui4rc --> observationyesNoeui4rc : "detail"

legend
  | <back:LightBlue> | Source Profile |
  | <back:LightGreen> | Target Profile |
endlegend

@enduml
