
@startuml
!define RECTANGLE class
skinparam linetype ortho

skinparam class {
    BackgroundColor<<source>> LightBlue
    BackgroundColor<<target>> LightGreen
}
RECTANGLE Encountereui4rc as "Encounter-eu-i4rc" <<source>> [[StructureDefinition-Encounter-eu-i4rc.html]]
RECTANGLE episodeOfCareeui4rc as "episodeOfCare-eu-i4rc" <<target>> [[StructureDefinition-episodeOfCare-eu-i4rc.html]]
Encountereui4rc --> episodeOfCareeui4rc : "episodeOfCare"

legend
  | <back:LightBlue> | Source Profile |
  | <back:LightGreen> | Target Profile |
endlegend

@enduml
