@startuml

scale 0.7

header Overview of IDEA4RC DataModel

title IDEA4RC DataModel Object Diagram

hide spot
hide circle

skinparam linetype ortho
scale 0.7

legend top left
|= |= Review Status |
|<back:#87e887>   </back>| First Block (stable) |
|<back:#94d8f2>   </back>| First Block (Rel. Cand.) |
|<back:#E5CCFF>   </back>| First Block (review) |
|<back:#FFB266>   </back>| Second Block  |
|<back:#FFFFCC>   </back>| Third Block |
endlegend

object "Patient" as p #94d8f2 {
}
url of p [[StructureDefinition-Subject.html]]

object "HospitalData" as hd #94d8f2 {
}
url of hd [[StructureDefinition-HospitalPatientRecords.html]]

object "HospitalPatientRecords" as hpr #94d8f2 {
}
url of hpr [[StructureDefinition-HospitalPatientRecords.html]]

object "PatientFollowUp" as pfu #94d8f2 {
}
url of pfu [[StructureDefinition-PatientFollowUp.html]]

object "CancerEpisode" as ce #94d8f2 {
}
url of ce [[StructureDefinition-CancerEpisode.html]]

object "Diagnosis" as d #94d8f2 {
}
url of d [[StructureDefinition-Diagnosis.html]]

object "EpisodeEvent" as ee #94d8f2 {
}
url of ee [[StructureDefinition-EpisodeEvent.html]]

object "PathologicalStage" as ps #94d8f2 {
}
url of ps [[StructureDefinition-PathologicalStage.html]]

object "ClinicalStage" as cs #94d8f2 {
}
url of cs [[StructureDefinition-ClinicalStage.html]]

object "GeneticTestExpression" as gte #94d8f2 {
}
url of gte [[StructureDefinition-GeneticTestExpression.html]]

object "Surgery" as su #94d8f2 {
}
url of su [[StructureDefinition-Surgery.html]]

object "SystemicTreatment" as st #94d8f2 {
}
url of st [[StructureDefinition-SystemicTreatment.html]]

object "Radiotherapy" as r #94d8f2 {
}
url of r [[StructureDefinition-Radiotherapy.html]]

object "IsolatedLimbPerfusion" as ilp #94d8f2 {
}
url of cs [[StructureDefinition-IsolatedLimbPerfusion.html]]

object "RegionalDeepHyperthemia" as rdh #94d8f2 {
}
url of cs [[StructureDefinition-RegionalDeepHyperthemia.html]]

object "DrugsForTreatments" as dft #94d8f2 {
}
url of cs [[StructureDefinition-DrugsForTreatments.html]]

object "OverallTreatmentResponse" as tr #94d8f2 {
}
url of tr [[StructureDefinition-TreatmentResponse.html]]

object "AdverseEvent" as ae #94d8f2 {
}
url of ae [[StructureDefinition-AdverseEvent.html]]

p "1" ||--|{ "1..N" hpr
p "1" ||--o{ "1..N" ce
p "1" ||--o{ "0..N" pfu

hpr "1..N" }|--|| "1" hd

ce "1" ||--|{ "1..N" d
ce "1" ||--|{ "0..N" ee

d "0..1" }o--|| "1" ee

ee "1" ||--o{ "0..N" r
ee "1" ||--o{ "0..N" su
ee "1" ||--o{ "0..N" st
ee "1" ||--o{ "0..N" rdh
ee "1" ||--o{ "0..N" ilp
ee "1" ||--o{ "0..N" gte
ee "1" ||--o{ "0..1" tr

d "1" ||--o{ "0..N" r
d "1" ||--o{ "0..N" su
d "1" ||--o| "0..1" ps
d "1" ||--o| "0..1" cs
d "1" ||--o{ "0..N" st
d "1" ||--o{ "0..N" rdh
d "1" ||--o{ "0..N" ilp
d "1" ||--o{ "0..N" gte
d "1" ||--o| "0..1" tr

r "1" ||--o{ "0..N" ae

su "1" ||--o{ "0..N" ae

st "0..N" }o--|| "1" ae
st "1" ||--|{ "0..N" dft

ilp "1" ||--|{ "0..N" dft
ilp "1" ||--|{ "0..N" rdh

@enduml

