@startuml
title IDEA4RC Model Map

!define RECTANGLE class

' avoid problems with angled crows feet
skinparam linetype ortho


legend top left
|= |= Review Status |
|<back:#LightBlue>   </back>| Logical Model |
|<back:#LightGreen>   </back>| Profile|
endlegend

skinparam class {
    BackgroundColor<<LogicalModel>> #LightBlue
    BackgroundColor<<Profile>> #LightGreen
}


RECTANGLE "AdverseEvent\n(logical model)" as AdverseEvent <<LogicalModel>>
url of AdverseEvent is [[StructureDefinition-AdverseEvent.html]]
RECTANGLE "AdverseEvent-eu-i4rc\n(profile)" as Target1 <<Profile>>
url of Target1 is [[StructureDefinition-AdverseEvent-eu-i4rc.html]]
AdverseEvent --> Target1

RECTANGLE "CancerEpisode\n(logical model)" as CancerEpisode <<LogicalModel>>
url of CancerEpisode is [[StructureDefinition-CancerEpisode.html]]
RECTANGLE "Condition-primaryCancer-eu-i4rc\n(profile)" as Target2 <<Profile>>
url of Target2 is [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
CancerEpisode --> Target2
RECTANGLE "Observation-diagnosis-eu-i4rc\n(profile)" as Target3 <<Profile>>
url of Target3 is [[StructureDefinition-Observation-diagnosis-eu-i4rc.html]]
CancerEpisode --> Target3

RECTANGLE "EpisodeEvent\n(logical model)" as EpisodeEvent <<LogicalModel>>
url of EpisodeEvent is [[StructureDefinition-EpisodeEvent.html]]
EpisodeEvent --> Target2
CancerEpisode -[hidden]-> EpisodeEvent


RECTANGLE "GeneticTestExpression\n(logical model)" as GeneticTestExpression <<LogicalModel>>
url of GeneticTestExpression is [[StructureDefinition-GeneticTestExpression.html]]
GeneticTestExpression --> Target2
EpisodeEvent -[hidden]-> GeneticTestExpression

RECTANGLE "HospitalPatientRecords\nHospital Data\n(logical model)" as HospitalPatientRecords <<LogicalModel>>
url of HospitalPatientRecords is [[StructureDefinition-HospitalPatientRecords.html]]
RECTANGLE "episodeOfCare-eu-i4rc\n(profile)" as Target7 <<Profile>>
url of Target7 is [[StructureDefinition-episodeOfCare-eu-i4rc.html]]
HospitalPatientRecords --> Target7

RECTANGLE "OtherTreatment\n(logical model)" as OtherTreatment <<LogicalModel>>
url of OtherTreatment is [[StructureDefinition-OtherTreatment.html]]
RECTANGLE "Procedure-otherTreatment-eu-i4rc\n(profile)" as Target8 <<Profile>>
url of Target8 is [[StructureDefinition-Procedure-otherTreatment-eu-i4rc.html]]
OtherTreatment --> Target8
EpisodeEvent -[hidden]-> OtherTreatment

RECTANGLE "PatientFollowUp\n(logical model)" as PatientFollowUp <<LogicalModel>>
url of PatientFollowUp is [[StructureDefinition-PatientFollowUp.html]]
RECTANGLE "Encounter-eu-i4rc\n(profile)" as Target9 <<Profile>>
url of Target9 is [[StructureDefinition-Encounter-eu-i4rc.html]]
PatientFollowUp --> Target9
RECTANGLE "CarePlan-eu-i4rc\n(profile)" as Target10 <<Profile>>
url of Target10 is [[StructureDefinition-CarePlan-eu-i4rc.html]]
PatientFollowUp --> Target10
RECTANGLE "observation-lastFollowupStatus-eu-i4rc\n(profile)" as Target11 <<Profile>>
url of Target11 is [[StructureDefinition-observation-lastFollowupStatus-eu-i4rc.html]]
PatientFollowUp --> Target11

RECTANGLE "Radiotherapy\n(logical model)" as Radiotherapy <<LogicalModel>>
url of Radiotherapy is [[StructureDefinition-Radiotherapy.html]]
RECTANGLE "Procedure-radiotheraphy-eu-i4rc\n(profile)" as Target12 <<Profile>>
url of Target12 is [[StructureDefinition-Procedure-radiotheraphy-eu-i4rc.html]]
Radiotherapy --> Target12
EpisodeEvent -[hidden]-> Radiotherapy


RECTANGLE "Surgery\n(logical model)" as Surgery <<LogicalModel>>
url of Surgery is [[StructureDefinition-Surgery.html]]
RECTANGLE "Procedure-surgery-eu-i4rc\n(profile)" as Target23 <<Profile>>
url of Target23 is [[StructureDefinition-Procedure-surgery-eu-i4rc.html]]
Surgery --> Target23
EpisodeEvent -[hidden]-> Surgery



@enduml
