@startuml

scale 0.7

header Overview of IDEA4RC DataModel

title IDEA4RC DataModel Object Diagram

hide spot
hide circle

skinparam linetype ortho
scale 0.7

legend top left
|= |= Review Status |
|<back:#87e887>   </back>| First Block (stable) |
|<back:#94d8f2>   </back>| First Block (Rel. Cand.) |
|<back:#E5CCFF>   </back>| First Block (review) |
|<back:#FFB266>   </back>| Second Block  |
|<back:#FFFFCC>   </back>| Third Block |
endlegend

object "Patient" as p #E5CCFF {
}
url of p [[StructureDefinition-Subject.html]]

object "HospitalData" as hd #E5CCFF {
}
url of hd [[StructureDefinition-HospitalPatientRecords.html]]

object "HospitalPatientRecords" as hpr #E5CCFF {
}
url of hpr [[StructureDefinition-HospitalPatientRecords.html]]

object "PatientFollowUp" as pfu #E5CCFF {
}
url of pfu [[StructureDefinition-PatientFollowUp.html]]

object "CancerEpisode" as ce #E5CCFF {
}
url of ce [[StructureDefinition-CancerEpisode.html]]

object "Diagnosis" as d #E5CCFF {
}
url of d [[StructureDefinition-Diagnosis.html]]

object "EpisodeEvent" as ee #E5CCFF {
}
url of ee [[StructureDefinition-EpisodeEvent.html]]

object "HnStage" as hs #E5CCFF {
}
object "SarcomaStage" as ss #E5CCFF {
}

object "PathologicalReportInfo" as pri {
}
object "GeneticTestExpression" as gte #FFFFCC {
}
url of gte [[StructureDefinition-GeneticTestExpression.html]]

object "Surgery" as su #E5CCFF {
}
url of su [[StructureDefinition-Surgery.html]]

object "SystemicTreatment" as st #FFFFCC {
}
url of st [[StructureDefinition-SystemicTreatment.html]]

object "Radiotherapy" as r #FFB266 {
}
url of r [[StructureDefinition-Radiotherapy.html]]

object "OtherLocalTreatment" as olt {
}

object "IsolatedLimbPerfusion" as ilp {
}
object "DrugsForTreatments" as dft {
}
object "TreatmentResponse" as tr #FFFFCC {
}
url of tr [[StructureDefinition-TreatmentResponse.html]]

object "AdverseEvent" as ae #FFFFCC {
}
url of ae [[StructureDefinition-AdverseEvent.html]]

p "1" ||--|{ "1..N" hpr
hd "1" ||--|{ "1..N" hpr
p "1" ||--o{ "0..N" ce
p "1" ||--o{ "0..N" pfu

ce "1" ||--o{ "1" d

d "1" ||--|{ "1..N" ee

ee "1" ||--o| "0..1" hs
ee "1" ||--o| "0..1" ss
st "1" ||--|{ "0..N" dft
ilp "1" ||--|{ "0..N" dft
olt "1" ||--|{ "0..N" dft
ee "1" ||--o{ "0..N" r
ee "1" ||--o{ "0..N" su
ee "1" ||--o{ "0..N" st
ee "1" ||--o{ "0..N" olt
ee "1" ||--o{ "0..N" ilp
ee "1" ||--o{ "0..N" gte
ee "1" ||--o{ "0..N" tr
ee "1" ||--o{ "0..N" pri

su "1" ||--o{ "0..N" ae
st "0..N" ||--o{ "1" ae
r "1" ||--o{ "0..N" ae

@enduml

