@startuml
<style>
title {
  HorizontalAlignment right
  FontSize 24
  FontColor blue
}

header {
  HorizontalAlignment center
  FontSize 18
  ' FontColor purple
}

footer {
  HorizontalAlignment left
  FontSize 28
  FontColor red
}

legend {
  FontSize 15
  BackGroundColor yellow
  Margin 10
  Padding 5
}

caption {
  FontSize 32
}

arrow {
  FontSize 18
  Padding 50
  Margin 50
}

</style>

header Draft

title IDEA4RC H&N DataModel

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "HospitalData" as hd {
}

entity "HospitalPatientRecords" as hpr {
}

entity "Patient" as p {
 
}

entity "CancerEpisode" as ce {
  
}

note left of ce::HPVStatus
  Mandatory for OROPHARYNGEAL (not oral cavity) carcinomas
end note

note left of ce::sSNasalCavityAndParanasalSinuses
  One of the subsite values must be present
end note

note left of ce::hSSquamous
  One of the subgroup values must be present
end note


entity "EpisodeEvent" as ee {
  
}

entity "PathologicalStage" as ps {
}

entity "ClinicalStage" as cs {
}

entity "Surgery" as surg {
}

entity "SystemicTreatment" as systreat {
}

entity "Radiotherapy" as radio {
}

note right of radio::rtSetting
  Mandatory (only if Intent=Curative OR Unknown)
end note

entity "TreatmentResponse" as treatresp {
  
}

entity "PatientFollowUp" as pfu {
  
}

entity "AdverseEvent" as ae {
}

entity "GeneTestExpression" as gte {

}


p "1" ||--|{ "1..N" hpr
hd "1..N" ||--|{ "1" hpr

p "0..N" ||--o{ "1" ce
ce "1..N" ||--|{ "1" ee
ee "1" ||--o{ "0..N" radio
ee "1" ||--o{ "0..N" surg
ee "1" ||--o{ "0..N" systreat
ee "1" ||--o| "0..1" ps
ee "0..1" ||--o| "1" cs

ce "0..1" ||--o{ "1" treatresp
ee "0..N" ||--o{ "1" gte

p "0..N" ||--o{ "1" pfu

note as N1
The relations to AdverseEvent are a XOR
end note

surg "1" ||--o{ "0..N" ae
'note on link: XOR
systreat "0..N" ||--o{ "1" ae
'note on link: XOR
radio "1" ||--o{ "0..N" ae
'note on link: XOR

surg .. N1
systreat .. N1
radio .. N1

legend
* Treatment response is related to the whole treatment or to each type of treatments?
* Cardinalities must be reviewed
* How to handle unknown values?
* PFU is OK?
* CancerEpisode can we have +1 Histology/Morphology?
--
red -> Mandatory
yellow -> Recommended
green -> Optional  
end legend


@enduml
