@startuml

<style>
title {
  HorizontalAlignment right
  FontSize 24
  FontColor blue
}

header {
  HorizontalAlignment center
  FontSize 18
  ' FontColor purple
}

footer {
  HorizontalAlignment left
  FontSize 28
  FontColor red
}

legend {
  FontSize 15
  BackGroundColor yellow
  Margin 10
  Padding 5
}

caption {
  FontSize 32
}

arrow {
  FontSize 18
  Padding 50
  Margin 50
}

</style>

header Draft

title IDEA4RC DataModel

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

object "Patient" as p {
    + <color:blue>Sex</color>
+ <color:red>Race</color>
- <color:blue>BirthYear</color>
+ <color:blue>CountryOfResidence</color>
+ <color:red>Smoking</color>
# <color:red>CigarettesOrCigarsSmokedPerDay</color>
+ <color:red>Alcohol</color>
# <color:red>BMI</color>
# <color:green>CharlsonComorbidityIndex</color>
+ <color:red>Comorbidity</color>
- <color:red>MyocardialInfarction</color>
- <color:red>CongestiveHeartFailure</color>
- <color:red>PeripheralVascularDisease</color>
- <color:red>CerebrovascularAccidentExceptHemiplegia</color>
- <color:red>Dementia</color>
- <color:red>ChronicPulmonaryDisease</color>
- <color:red>ConnectiveTissueDisease</color>
- <color:red>Ulcer</color>
- <color:red>MildLiverDisease</color>
- <color:red>ModerateToSevereLiverDisease</color>
- <color:red>DiabetesWithoutComplications</color>
- <color:red>DiabetesWithEndOrganDamage</color>
- <color:red>Hemiplegia</color>
- <color:red>ModerateToSevereRenalDisease</color>
- <color:red>SolidTumorNonMetastatic</color>
- <color:red>MetastaticSolidTumor</color>
- <color:red>Leukemia</color>
- <color:red>Lymphoma</color>
- <color:red>MultipleMyeloma</color>
- <color:red>Aids</color>
# <color:red>ecogPS</color>
# <color:red>ecogPS</color>
# <color:red>KarnofsyIndexAtDiagnosis</color>
# <color:red>KarnofsyIndexLabel</color>
+ <color:green>NoGeneticSyndromeWho2020</color>
+ <color:green>OlliersDisease</color>
+ <color:green>MaffuciSyndrome</color>
+ <color:green>liFraumeniSyndrome</color>
+ <color:green>mcCuneAlbrightSyndrome</color>
+ <color:green>MultipleOsteochondromas</color>
+ <color:green>NeurofibromatosisType1</color>
+ <color:green>rothmundThomsonSyndrome</color>
+ <color:green>WernerSyndrome</color>
+ <color:green>Retinoblastoma</color>
+ <color:green>PagetDisease</color>
+ <color:green>OtherGeneticSyndromeWho2020</color>
+ <color:green>OccurrenceOfOtherCancer</color>
+ <color:green>PreviousCancerTreatment</color>

    }
object "HospitalData" as hd {
    + <color:red>hospitalName</color>

    }
object "HospitalPatientRecords" as hpr {
    + <color:red>patient</color>
+ <color:red>hospitalData</color>
+ <color:red>dateOfFirstContactWithTheHospital</color>

    }
object "PatientFollowUp" as pfu {
    + <color:blue>Patient</color>
+ <color:blue>statusAtLastFollowUp</color>
+ <color:blue>PatientFollowUpDate</color>
+ <color:red>NewCancerDiagnosis</color>
+ <color:red>DateOfNewCancerDiagnosis</color>
+ <color:red>NewCancerTopography</color>
+ <color:green>LastContact</color>

    }
object "CancerEpisode" as ce {
    + <color:blue>Patient</color>
+ <color:blue>dateOfDiagnosis</color>
+ <color:green>TypeOfBiopsy</color>
+ <color:blue>BiopsyDoneBy</color>
+ <color:blue>AgeAtDiagnosis</color>
+ <color:green>RadiotherapyInducedSarcoma</color>
- <color:blue>Grading</color>
+ <color:red>HistologySquamous</color>
+ <color:red>HistologyAdenocarcinoma</color>
+ <color:red>HistologyNeuroendocrine</color>
+ <color:red>HistologyOdontogenicCarcinoma</color>
+ <color:red>HistologySNUC</color>
+ <color:green>HistologySubgroupAdipocyticTumours</color>
+ <color:green>histologySubgroupFmtTumours</color>
+ <color:green>histologySubgroupSocalledFibrohistiocyticTumours</color>
+ <color:green>VascularTumours</color>
+ <color:green>pericyticPerivascularTumours</color>
+ <color:green>SmoothMuscleTumours</color>
+ <color:green>SkeletalMuscleTumours</color>
+ <color:green>chondroOsseousTumours</color>
+ <color:green>PeripheralNerveSheathTumours</color>
+ <color:green>TumoursOfUncertainDifferentiation</color>
+ <color:green>undifSmallRCelSarcBonAndSofTis</color>
+ <color:green>estAndRelatedTumours</color>
+ <color:green>MiscellaniousMesenchimalTumors</color>
+ <color:green>MixedEpithelialAndMesenchymalTumours</color>
+ <color:red>NasalCavityAndParanasalSinusesSubsite</color>
+ <color:red>NasopharynxSubsite</color>
+ <color:red>HypopharynxSubsite</color>
+ <color:red>OropharynxSubsite</color>
+ <color:red>LarynxSubsite</color>
+ <color:red>OralCavitySubsite</color>
+ <color:red>LipSubsite</color>
+ <color:green>UpperAndLowerLimbsSubsite</color>
+ <color:green>TrunkWallSubsite</color>
+ <color:green>IntraAbdominalSubsite</color>
+ <color:green>IntraThoracicSubsite</color>
+ <color:green>GenitoUrinarySubsite</color>
+ <color:green>HeadAndNeckSubsite</color>
+ <color:green>BreastSubsite</color>
+ <color:green>OtherSubsite</color>
+ <color:green>TumorSize</color>
+ <color:green>Depth</color>
+ <color:green>BiopsyMitoticCount</color>
# <color:red>PlasmaticEbvDnaAtBaseline</color>
- <color:red>HpvStatus</color>
- <color:red>crpCReactiveProteinTested</color>

    }
object "EpisodeEvent" as ee {
    + <color:blue>cancerEpisode</color>
+ <color:blue>EventType</color>
- <color:blue>DefinedAt</color>
+ <color:blue>DateOfEpisode</color>

    }
object "HnStage" as hs {
    + <color:red>episodeEvent</color>
+ <color:red>Ct</color>
+ <color:red>Cn</color>
+ <color:red>Cm</color>
+ <color:red>Pt</color>
+ <color:red>Pn</color>
+ <color:red>Pm</color>
+ <color:red>rEne</color>
+ <color:red>StagingClassification</color>
# <color:red>SoftTissue</color>
# <color:red>DistantLymphNode</color>
# <color:red>Lung</color>
# <color:red>Bone</color>
# <color:red>Liver</color>
# <color:red>Pleura</color>
# <color:red>Peritoneum</color>
# <color:red>Brain</color>
# <color:red>OtherViscera</color>
# <color:red>Unknown</color>

    }
object "SarcomaStage" as ss {
    + <color:green>episodeEvent</color>
+ <color:green>Localised</color>
+ <color:green>locoRegional</color>
+ <color:green>RegionalNodalMetastases</color>
# <color:green>SoftTissue</color>
# <color:green>DistantLymphNode</color>
# <color:green>Lung</color>
# <color:green>Bone</color>
# <color:green>Liver</color>
# <color:green>Pleura</color>
# <color:green>Peritoneum</color>
# <color:green>Brain</color>
# <color:green>OtherViscera</color>
# <color:green>Unknown</color>

    }
object "PathologicalReportInfo" as pri {
    + <color:green>episodeEvent</color>
- <color:green>DegreeOfCytologicAtypia</color>
- <color:green>PatternOfGrowth</color>
- <color:green>MitoticActivity</color>
- <color:green>InfiltrationOfSurroundingMyometrium</color>
- <color:green>TypeOfNecrosis</color>
- <color:green>expressionOfErPr</color>
- <color:green>VascularIntrusionOrInvasion</color>
- <color:green>P16AndP53Expression</color>

    }
object "GeneticTestExpression" as gte {
    + <color:red>episodeEvent</color>
# <color:red>GeneExpressionAnalysisPerformed</color>
- <color:red>DateOfGeneExpression</color>
# <color:red>GeneMutationAnalysisPerformed</color>
- <color:red>DateOfGeneMutation</color>
# <color:red>TestsForChromosomeTranslocationsPerformed</color>
- <color:red>DateOfTraslocation</color>
# <color:red>ngsPerformed</color>
- <color:red>DateOfNgs</color>
# <color:red>pcrTestPerformed</color>
- <color:red>DateOfPcr</color>
# <color:red>ImmunohistochemistryPerformed</color>
- <color:red>DateOfImmunohistochemistry</color>
# <color:red>ctDnaPerformed</color>
- <color:red>DateOfCtdna</color>

    }
object "Surgery" as su {
    + <color:blue>episodeEvent</color>
+ <color:green>SurgeryType</color>
+ <color:red>SurgeryHospital</color>
+ <color:blue>DateOfSurgery</color>
+ <color:blue>SurgeryIntention</color>
+ <color:red>TypeOfSurgicalApproachOnTumour</color>
+ <color:blue>MarginsAfterSurgery</color>
+ <color:green>TumorRupture</color>
+ <color:green>SurgicalSpecimenMitoticCount</color>
+ <color:green>SurgicalSpecimenGradingOnlyInUntreatedTumours</color>
+ <color:green>IsolatedLimbPerfusion</color>
+ <color:red>Reconstruction</color>
+ <color:red>NeckSurgery</color>
+ <color:red>DateOfNeckSurgey</color>
+ <color:red>LateralityOfTheDissection</color>
+ <color:red>SurgeryOnM</color>
+ <color:red>DateOfSurgeryOnM</color>
- <color:red>siteOfSurgeryOnMetastasisSoftTissue</color>
- <color:red>siteOfSurgeryOnMetastasisDistantLymphNodes</color>
- <color:red>siteOfSurgeryOnMetastasisLung</color>
- <color:red>siteOfSurgeryOnMetastasisBone</color>
- <color:red>siteOfSurgeryOnMetastasisLiver</color>
- <color:red>siteOfSurgeryOnMetastasisPleura</color>
- <color:red>siteOfSurgeryOnMetastasisPeritoneum</color>
- <color:red>siteOfSurgeryOnMetastasisBrain</color>
- <color:red>siteOfSurgeryOnMetastasisOtherViscera</color>
- <color:red>siteOfSurgeryOnMetastasisUnknown</color>
+ <color:red>surgicalComplications</color>

    }
object "SystemicTreatment" as st {
    + <color:blue>episodeEvent</color>
+ <color:blue>TypeOfSystemicTreatment</color>
+ <color:red>Intent</color>
+ <color:red>Setting</color>
- <color:green>ChemotherapyInfo</color>
+ <color:blue>StartDateSystemicTreatment</color>
+ <color:blue>EndDateSystemicTreatment</color>
- <color:blue>numberOfCyclesAdministrations</color>
+ <color:red>StartDateRegimenChanged</color>
+ <color:red>EndDateRegimenChanged</color>
+ <color:blue>ReasonForEndOfTreatment</color>
+ <color:blue>treatmentResponse</color>

    }
object "Radiotherapy" as r {
    + <color:blue>episodeEvent</color>
+ <color:blue>Radiotherapy</color>
+ <color:blue>Intent</color>
- <color:blue>Setting</color>
+ <color:red>BeamQuality</color>
- <color:red>otherSpecify</color>
+ <color:red>TreatmentTechnique</color>
+ <color:blue>totalDoseGy</color>
+ <color:blue>NumberOfFractions</color>
- <color:red>AdaptiveRt</color>
- <color:red>igrt</color>
+ <color:blue>StartDate</color>
+ <color:blue>EndDate</color>
- <color:red>PrimaryOnly</color>
- <color:red>NeckOnly</color>
+ <color:red>PrimaryAndIpsilateralNeck</color>
+ <color:red>PrimaryAndBilateralNeck</color>
+ <color:red>DistantMetastasis</color>
# <color:blue>Lung</color>
# <color:blue>Mediastinum</color>
# <color:blue>Bone</color>
# <color:blue>SoftTissue</color>
# <color:blue>Liver</color>
+ <color:blue>TreatmentCompletedAsPlanned?</color>
+ <color:green>RegionalDeepHyperthemia</color>
- <color:green>Rdh_Startdate</color>
- <color:green>Rdh_Enddate</color>
# <color:green>ClinicalTreatmentResponse</color>

    }
object "OtherLocalTreatment" as olt {
    + <color:green>episodeEvent</color>
+ <color:green>episodeEvent</color>
+ <color:green>StartDate</color>
+ <color:green>EndDate</color>
- <color:green>IsolatedlimbperfusionReference</color>
# <color:green>treatmentResponse</color>

    }
object "IsolatedLimbPerfusion" as ilp {
    + <color:green>episodeEvent</color>
+ <color:green>episodeEvent</color>
+ <color:green>StartDate</color>
+ <color:green>EndDate</color>
# <color:green>treatmentResponse</color>

    }
object "DrugsForTreatments" as dft {
    + <color:blue>drugTreatment</color>
+ <color:blue>Drug</color>

    }
object "TreatmentResponse" as tr {
    + <color:blue>episodeEvent</color>
+ <color:blue>treatmentResponse</color>
+ <color:blue>treatmentResponseDefinedDone</color>

    }
object "AdverseEvent" as ae {
    + <color:red>episodeEvent</color>
+ <color:red>adverseEventType</color>
+ <color:red>AdverseEventStartingDate</color>
+ <color:red>AdverseEventDuration</color>

    }
p "1" ||--|{ "1..N" hpr
hd "1" ||--|{ "1..N" hpr

p "1" ||--o{ "0..N" ce
p "1" ||--o{ "0..N" pfu

ce "1" ||--|{ "1..N" ee

ee "1" ||--o| "0..1" hs
ee "1" ||--o| "0..1" ss

st "1" ||--|{ "0..N" dft
ilp "1" ||--|{ "0..N" dft
olt "1" ||--|{ "0..N" dft

ee "1" ||--o{ "0..N" r
ee "1" ||--o{ "0..N" su
ee "1" ||--o{ "0..N" st
ee "1" ||--o{ "0..N" olt
ee "1" ||--o{ "0..N" ilp
ee "1" ||--o{ "0..N" gte
ee "1" ||--o{ "0..N" tr
ee "1" ||--o{ "0..N" pri


note as N1
The relations to AdverseEvent are a XOR
end note

su "1" ||--o{ "0..N" ae
'note on link: XOR
st "0..N" ||--o{ "1" ae
'note on link: XOR
r "1" ||--o{ "0..N" ae
'note on link: XOR

s .. N1
st .. N1
r .. N1
legend
Text color:
Blue -> H&N, Sarc. 
Red -> H&N
Green -> Sarc.
---------
Shapes:
red -> Mandatory
yellow -> Recommended
green -> Optional
---------
Each variable (and entity if needed) is related to the datamodels,
HN means Head and Neck
S means Sarcoma
end legend
@enduml