@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "RadiotherapyI4rc" <<LogicalModel>> [[StructureDefinition-RadiotherapyI4rc.html]]
class "Procedure-radiotheraphy-eu-i4rc" <<Profile>> [[StructureDefinition-Procedure-radiotheraphy-eu-i4rc.html]]
"RadiotherapyI4rc" --> "Procedure-radiotheraphy-eu-i4rc"
@enduml