@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "AdverseEvent" <<LogicalModel>> [[StructureDefinition-AdverseEvent.html]]
note right #PaleTurquoise [[ConceptMap-adverseEvent2FHIR.html]]
Concept Map
endnote
class "AdverseEvent-eu-i4rc" <<Profile>> [[StructureDefinition-AdverseEvent-eu-i4rc.html]]
"AdverseEvent" --> "AdverseEvent-eu-i4rc"
@enduml