@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "EpisodeEvent" <<LogicalModel>> [[StructureDefinition-EpisodeEvent.html]]
note right #PaleTurquoise [[ConceptMap-episodeEvent2FHIR.html]]
Concept Map
endnote
class "Condition-primaryCancer-eu-i4rc" <<Profile>> [[StructureDefinition-Condition-primaryCancer-eu-i4rc.html]]
"EpisodeEvent" --> "Condition-primaryCancer-eu-i4rc"
@enduml