@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "SarcomaStage" <<LogicalModel>> [[StructureDefinition-SarcomaStage.html]]
note right #PaleTurquoise [[ConceptMap-sarcomaStage2FHIR.html]]
Concept Map
endnote
class "sarcoma-cancer-stage-group" <<Profile>> [[StructureDefinition-sarcoma-cancer-stage-group.html]]
"SarcomaStage" --> "sarcoma-cancer-stage-group"
class "sarcoma-extent-category" <<Profile>> [[StructureDefinition-sarcoma-extent-category.html]]
"SarcomaStage" --> "sarcoma-extent-category"
"sarcoma-cancer-stage-group" -[hidden]-> "sarcoma-extent-category"
class "locoRegional-category" <<Profile>> [[StructureDefinition-locoRegional-category.html]]
"SarcomaStage" --> "locoRegional-category"
"sarcoma-extent-category" -[hidden]-> "locoRegional-category"
class "Condition-secondaryCancer-eu-i4rc" <<Profile>> [[StructureDefinition-Condition-secondaryCancer-eu-i4rc.html]]
"SarcomaStage" --> "Condition-secondaryCancer-eu-i4rc"
"locoRegional-category" -[hidden]-> "Condition-secondaryCancer-eu-i4rc"
@enduml