@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "Subject" <<LogicalModel>> [[StructureDefinition-Subject.html]]
class "patient-eu-i4rc" <<Profile>> [[StructureDefinition-patient-eu-i4rc.html]]
"Subject" --> "patient-eu-i4rc"
class "observation-tobaccouse-eu-i4rc" <<Profile>> [[StructureDefinition-observation-tobaccouse-eu-i4rc.html]]
"Subject" --> "observation-tobaccouse-eu-i4rc"
"patient-eu-i4rc" -[hidden]-> "observation-tobaccouse-eu-i4rc"
class "observation-alcoholuse-eu-i4rc" <<Profile>> [[StructureDefinition-observation-alcoholuse-eu-i4rc.html]]
"Subject" --> "observation-alcoholuse-eu-i4rc"
"observation-tobaccouse-eu-i4rc" -[hidden]-> "observation-alcoholuse-eu-i4rc"
class "observation-comorbidity-eu-i4rc" <<Profile>> [[StructureDefinition-observation-comorbidity-eu-i4rc.html]]
"Subject" --> "observation-comorbidity-eu-i4rc"
"observation-alcoholuse-eu-i4rc" -[hidden]-> "observation-comorbidity-eu-i4rc"
class "observation-karnofsky-performance-statuseu-i4rc" <<Profile>> [[StructureDefinition-observation-karnofsky-performance-statuseu-i4rc.html]]
"Subject" --> "observation-karnofsky-performance-statuseu-i4rc"
"observation-comorbidity-eu-i4rc" -[hidden]-> "observation-karnofsky-performance-statuseu-i4rc"
class "observation-ecog-performance-status-eu-i4rc" <<Profile>> [[StructureDefinition-observation-ecog-performance-status-eu-i4rc.html]]
"Subject" --> "observation-ecog-performance-status-eu-i4rc"
"observation-karnofsky-performance-statuseu-i4rc" -[hidden]-> "observation-ecog-performance-status-eu-i4rc"
class "observation-cci-eu-i4rc" <<Profile>> [[StructureDefinition-observation-cci-eu-i4rc.html]]
"Subject" --> "observation-cci-eu-i4rc"
"observation-ecog-performance-status-eu-i4rc" -[hidden]-> "observation-cci-eu-i4rc"
class "bmi" <<Profile>> [[StructureDefinition-bmi.html]]
"Subject" --> "bmi"
"observation-cci-eu-i4rc" -[hidden]-> "bmi"
class "observation-occurrencOtherCancer-eu-i4rc" <<Profile>> [[StructureDefinition-observation-occurrencOtherCancer-eu-i4rc.html]]
"Subject" --> "observation-occurrencOtherCancer-eu-i4rc"
"bmi" -[hidden]-> "observation-occurrencOtherCancer-eu-i4rc"
class "observation-treatment-eu-i4rc" <<Profile>> [[StructureDefinition-observation-treatment-eu-i4rc.html]]
"Subject" --> "observation-treatment-eu-i4rc"
"observation-occurrencOtherCancer-eu-i4rc" -[hidden]-> "observation-treatment-eu-i4rc"
@enduml