Instance: observation-id-23
InstanceOf: ObservationComorbidities
Title: "Observation: comorbidity"
Usage: #example
// * meta.profile = "http://hl7.eu/fhir/ig/idea4rc/StructureDefinition/observation-comorbidity-eu-i4rc"
* extension[0].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4329847 "Myocardial infarction"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#319835 "Congestive heart failure"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
* extension[=].valueCodeableConcept = $athena#321052 "Peripheral vascular disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#381316 "Cerebrovascular accident"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
* extension[=].valueCodeableConcept = $athena#4182210 "Dementia"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#1620830 "Chronic pulmonary disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4344165 "Undifferentiated connective tissue disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
* extension[=].valueCodeableConcept = $athena#4177703 "Ulcer"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#1621281 "Mild liver or renal disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
* extension[=].valueCodeableConcept = $cs-generic-eu-i4rc#1620421-liver "Moderate or severe liver disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $cs-generic-eu-i4rc#1620421-renal "Moderate or severe renal disease"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#1620816 "Diabetes without complications"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#1620753 "Diabetes with end organ damage"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#374022 "Hemiplegia"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#1621181 "Metastatic solid tumor"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $cs-generic-eu-i4rc#solid-tumor "Solid tumor (non metastatic)"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#317510 "Leukemia"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#45881968 "Lymphoma"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#437233 "Multiple myeloma"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#45884125 "AIDS"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4211787 "No evidence of"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4145177 "Enchondromatosis"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
* extension[=].valueCodeableConcept = $athena#4187683 "Maffucci syndrome"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4323645 "Li-Fraumeni syndrome"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#37117262 "McCune Albright syndrome"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#37396802 "Multiple osteochondroma"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#377252 "Neurofibromatosis type 1"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4286355 "Rothmund-Thomson syndrome"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4197821 "Werner syndrome"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#4158977 "Retinoblastoma"
* extension[+].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"
* extension[=].valueCodeableConcept = $athena#75910 "Osteitis deformans"
* status = #final
* code = $loinc#75618-9 "Comorbid condition"
* subject = Reference(patient-id-17)
* valueQuantity.value = 2